In [3]:
import numpy as np

In [3]:
np.__version__

'2.2.5'

## Create & Read

#### id Array

In [4]:
arra1 = np.array([1,2,3,4,5])

In [5]:
arra1

array([1, 2, 3, 4, 5])

In [6]:
type(arra1)

numpy.ndarray

In [7]:
arra1.shape

(5,)

In [8]:
arra1.dtype

dtype('int64')

In [9]:
arra1.ndim

1

In [10]:
arra1.size

5

#### 2d Array

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 3)

In [15]:
arr2.dtype

dtype('int64')

In [16]:
arr2.size

6

#### 3d Array

In [17]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,5,7],[57,9,0]]])

In [18]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  5,  7],
        [57,  9,  0]]])

In [19]:
arr3.ndim

3

In [20]:
arr3.shape

(2, 2, 3)

In [21]:
arr3.size

12

## create random Array

In [4]:
randomArr = np.random.rand(3,2,3)

In [5]:
randomArr

array([[[0.70581666, 0.27203309, 0.97108376],
        [0.82042348, 0.40922635, 0.7624299 ]],

       [[0.63505381, 0.34415534, 0.3336118 ],
        [0.50528871, 0.52703781, 0.44927042]],

       [[0.9084247 , 0.39857583, 0.29326729],
        [0.66900654, 0.7041322 , 0.87295289]]])

In [6]:
zeroas = np.zeros((3,2,3))

In [7]:
zeroas

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
zeroas.ndim

3

In [9]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [10]:
ones = np.ones((3,2,3))

In [11]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
arr3

NameError: name 'arr3' is not defined

In [13]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,5,7],[57,9,0]]])

In [14]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  5,  7],
        [57,  9,  0]]])

In [15]:
 arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr3[0][0][0]

np.int64(1)

In [17]:
arr3[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  5,  7],
        [57,  9,  0]]])

In [19]:
arr3[-1]

array([[ 1,  5,  7],
       [57,  9,  0]])

In [20]:
arr3[1][0][1]

np.int64(5)

In [21]:
arr3[1,0,1]

np.int64(5)

## Update & Delete

In [22]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)



In [23]:
a1

array([[[0.88448535, 0.70815173],
        [0.8917813 , 0.73413076],
        [0.66960666, 0.61954638]],

       [[0.12435228, 0.45669504],
        [0.71754782, 0.21916793],
        [0.63803794, 0.33880545]]])

In [24]:
a2

array([[[0.19021027, 0.53394066],
        [0.95248408, 0.2653854 ],
        [0.30657392, 0.57815009]],

       [[0.29878584, 0.89078213],
        [0.88686527, 0.93505014],
        [0.46268972, 0.00359656]]])

In [25]:
np.add(a1,a2)

array([[[1.07469562, 1.24209238],
        [1.84426539, 0.99951616],
        [0.97618058, 1.19769647]],

       [[0.42313812, 1.34747717],
        [1.60441309, 1.15421808],
        [1.10072766, 0.34240201]]])

In [26]:
np.subtract(a1,a2)

array([[[ 0.69427508,  0.17421107],
        [-0.06070278,  0.46874537],
        [ 0.36303273,  0.04139629]],

       [[-0.17443356, -0.43408708],
        [-0.16931745, -0.71588221],
        [ 0.17534822,  0.3352089 ]]])

In [27]:
np.divide(a1,a2)

array([[[ 4.65003998,  1.32627422],
        [ 0.93626898,  2.7662817 ],
        [ 2.1841605 ,  1.07160129]],

       [[ 0.41619201,  0.51268995],
        [ 0.80908323,  0.23439164],
        [ 1.37897582, 94.20274682]]])

In [28]:
np.multiply(a1,a2)

array([[[0.1682382 , 0.378111  ],
        [0.8494075 , 0.19482758],
        [0.20528394, 0.35819079]],

       [[0.0371547 , 0.40681578],
        [0.63636824, 0.20493301],
        [0.2952136 , 0.00121853]]])

## statistical operation

In [29]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [30]:
sqrt

np.float64(5.0)

In [31]:
abs

np.int64(2)

In [32]:
power

np.int64(256)

In [33]:
log

np.float64(3.2188758248682006)

In [34]:
mins

np.float64(0.12435227909753621)

In [35]:
maxs

np.float64(0.9524840826641741)

#### Update

In [37]:
arr4 = np.array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [38]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [39]:
arr4[0, 0, 2] = 500
arr4

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [40]:
arr4.sort()
arr4

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

# reshape

In [41]:
arr4.shape

(3, 2, 3)

In [42]:
arr4_reshape= arr4.reshape((2,3,3))
arr4_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [43]:
arr4_reshape= arr4.reshape((2,3,-1))
arr4_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [44]:
zeros

NameError: name 'zeros' is not defined

In [45]:
zeroas

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
#create new array

new_array = np.ones((3,2,3))


In [47]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [49]:
appd = np.append(zeroas, new_array, axis=0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [50]:
#insert

In [51]:
zeroas

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [52]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
inserted_array = np.insert(zeroas, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#Delete

In [57]:
arr5 = np.random.rand(3, 2, 3)
arr5

array([[[0.18838079, 0.94428171, 0.77688009],
        [0.41839652, 0.54567045, 0.09124607]],

       [[0.72919589, 0.958311  , 0.366492  ],
        [0.87159187, 0.30501034, 0.50636027]],

       [[0.90623822, 0.79348172, 0.75951127],
        [0.03141004, 0.61273746, 0.71520866]]])

In [58]:
# delete the array
arr6 = np.delete(arr5, 0, axis=1)

In [60]:
arr6 

array([[[0.41839652, 0.54567045, 0.09124607]],

       [[0.87159187, 0.30501034, 0.50636027]],

       [[0.03141004, 0.61273746, 0.71520866]]])

In [61]:
np.save("new_array", arr6)

In [62]:
np.load("new_array.npy")

array([[[0.41839652, 0.54567045, 0.09124607]],

       [[0.87159187, 0.30501034, 0.50636027]],

       [[0.03141004, 0.61273746, 0.71520866]]])